package com.avaliacaoteste.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetaNotaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaNotaAllPropertiesEquals(MetaNota expected, MetaNota actual) {
        assertMetaNotaAutoGeneratedPropertiesEquals(expected, actual);
        assertMetaNotaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaNotaAllUpdatablePropertiesEquals(MetaNota expected, MetaNota actual) {
        assertMetaNotaUpdatableFieldsEquals(expected, actual);
        assertMetaNotaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaNotaAutoGeneratedPropertiesEquals(MetaNota expected, MetaNota actual) {
        assertThat(actual)
            .as("Verify MetaNota auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaNotaUpdatableFieldsEquals(MetaNota expected, MetaNota actual) {
        assertThat(actual)
            .as("Verify MetaNota relevant properties")
            .satisfies(a -> assertThat(a.getArea()).as("check area").isEqualTo(expected.getArea()))
            .satisfies(a -> assertThat(a.getMeta()).as("check meta").isEqualTo(expected.getMeta()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaNotaUpdatableRelationshipsEquals(MetaNota expected, MetaNota actual) {
        assertThat(actual)
            .as("Verify MetaNota relationships")
            .satisfies(a -> assertThat(a.getAluno()).as("check aluno").isEqualTo(expected.getAluno()));
    }
}
